### ISSUE TITLE
What does it do?  AXP2101_Class::setReg0x20Bit0(bool flg)

### ISSUE THREAD

**Issue by louisbertrand** [m5stack/M5Unified#111]
What does this method do?
AXP2101_Class::setReg0x20Bit0(bool flg)
I'm asking because the AXP2101 datasheet refers to register 0x20 as PWRON status and the bits are marked RO read-only. What's the point of trying to set a read-only bit?
Or are we talking about a different register 20?
In other words, please document this method. 
Thanks

**Comment by lovyan03** [comment]
Hello, @louisbertrand 
I don't know much about this either.
I think it's a remnant from when I was referring to code that used features that weren't in the specs.
I don't think it's necessary, so I'll remove this feature.

**Comment by louisbertrand** [comment]
OK thanks!
