### ISSUE TITLE
getVBUSVoltage not working with Core2 v1.1

### ISSUE THREAD

**Issue by forstner-m** [m5stack/M5Unified#115]
Hello,

the function always returns zero, even though a USB cable is connected.

`float getVBUSVoltage(void);`

This function also returns false.

`bool isVBUS(void);`

There is a bug somewhere and please correct it.

Thank you!

Best regards,
Michael

**Comment by felmue** [comment]
Hello @forstner-m 

`bool isVBUS(void);` works for me just fine with M5Unified v0.1.16.

In order to get a value from `float getVBUSVoltage(void);` you'll first need to enable the ADC measurement by calling `setAdcState(true);`.

Thanks
Felix

**Comment by forstner-m** [comment]
v0.1.16 works!
