### ISSUE TITLE
[Request] Power Button State

### ISSUE THREAD

**Issue by Dreadnoise** [m5stack/M5Unified#137]
I'm wondering if it is possible to get the power button state at all?

I noticed in the AXP2101_Class for the unified library that there was functions like "isPekeyShortPressIrq()" and was curious if this is for the button and if so can it be added to the library, or is there a work around at all?

**Comment by lovyan03** [comment]
Hello, @Dreadnoise 
You can use `M5.BtnPWR.wasClicked()` and `M5.BtnPWR.wasHold()`
