### ISSUE TITLE
非同期のaquestalkのexampleありませんか？

### ISSUE THREAD

**Issue by mayopan** [m5stack/M5Unified#17]
いつも使いやすいライブラリ提供ありがとうございます。
lovyangfxとaquestalkを組み合わせてm5stackcore2のコード書いてましたが、タッチ操作も追加したくなり、ちょうどm5の機能が統合されたm5unifiedが使えそうなので試しました。
setup内での再生はうまくいくのですが、loop内で非同期再生しようとaquesTTSを修正して試しましたが、うまく行きません。
音は出ますが細切れの超スロー再生のような感じになってしまいます。
非同期バージョンのexampleがあると嬉しいです。

**Comment by mayopan** [comment]
上記、解決しました。exampleもloop内再生ありましたね。失礼しました。
音声出力バッファの長さLEN_FRAMEをデフォルトの32から255以上くらいにすると、loop内でも途切れず再生できました。
exampleではLEN_FRAMEがデフォルトの32でも問題なく再生できているんですが、私のコードではudpを動かしているのが影響しているようです。

**Comment by lovyan03** [comment]
お待たせいたしました。
AquesTalkのサンプルを更新し、developブランチを更新いたしました。
音声再生を別タスクで実行する構成に変更いたしましたので、ぜひお試しください。
