### ISSUE TITLE
ATOM QR-CODE Kit

### ISSUE THREAD

**Issue by JORGEGO** [m5stack/M5Unified#23]
Dear M5Stack team.
we have selected M5Stack technology with nanoFramework as strategy technology for our smart devices.
We have started developing and we have found the first critical point. We need to use the ATOM QR-CODE Kit on the nanoFramework image, but the only place that I have found until now to read QR code is downloading and burd directly with your tool, but that is not the solution.
I need a wrapper solution in C# language to access the QR reader information.
Could you help me?

Thanks it is so important at that moment take the right decision.

**Comment by lovyan03** [comment]
@JORGEGO
Hello. My name is Lovyan and I am the outsourced maintainer of the M5Unified library.

In this repository there is a C++ library for building applications using ArduinoESP32 or ESP-IDF.
As C# or nano Framework are not in charge of this repository, I apologize that I cannot give you a satisfactory answer.

I have never used ATOM_QRCODE, but from reading the sample code and the specification, it seems to be available as long as you can communicate via UART.

The manual and command specifications can be found here.
https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/atombase/AtomicQR/USER_MANUAL_QR-CODE_EN.docx
https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/atombase/AtomicQR/ATOM_QRCODE_CMD_EN.pdf

Sample code in C++ can be found here.
https://github.com/m5stack/M5-ProductExampleCodes/blob/master/AtomBase/AtomicQR/AtomicQR/AtomicQR.ino

Perhaps the implementation you would do is as follows
 - Serial communication using GPIO19 and GPIO22.
 - To set GPIO23 LOW to instruct the camera to take a picture.
 - Read data when GPIO33 is HIGH.

I Hope your project goes well.
Best regards.
