### ISSUE TITLE
Touch get wrong values more you go away from display center

### ISSUE THREAD

**Issue by gmgunderground** [m5stack/M5Unified#32]
M5.Touch get wrong X and Y values more you go away from display center. The same problem there is with M5Core2.
How to fix it? With this type of issue the display touch is compliteli useless. X and Y are not centered with the touch point.

https://user-images.githubusercontent.com/3244031/173841585-67615997-15f1-4aa2-a36c-80b45756c9c1.mp4

**Comment by gmgunderground** [comment]
> 

Thanks for the code, it actually helps a bit to improve the touch behavior, but it still remains quite inaccurate. Especially in the corners, the measured values of X and Y are quite wrong, significantly improving towards the center of the screen

**Comment by lovyan03** [comment]
@gmgunderground 
Have you tried adjusting data?
If it always shifts toward the center, I think you can compensate by changing the calibration value closer to the center.
For example, try the following .

```
  uint16_t data[8];

  data[0] =  32;   // left top X
  data[1] =  32;   // left top Y
  data[2] =  32;   // left bottom X
  data[3] = 207;   // left bottom Y
  data[4] = 287;   // right top X
  data[5] =  32;   // right top Y
  data[6] = 287;   // right bottom X
  data[7] = 207;   // right bottom Y

  M5.Display.setTouchCalibrate(data);
```

---
BTW, there is an update to the Core2 touch panel firmware.
This reduces the problem of coordinates being shifted vertically at the top of the screen.
( It may have already been updated if your purchase was recent. )

Try to write `Core2_Tools` once using `M5Burner`.
If the touch panel firmware is out of date, `Core2_Tools` will perform the update at startup.

Once the firmware update is performed, it will remain effective even if other programs are written thereafter.

**Comment by gmgunderground** [comment]
I installed M5 Tools and it updated the display firmware at startup. Now the touch screen seems to be doing much better.
Thank you

**Comment by gmgunderground** [comment]
> @gmgunderground Have you tried adjusting data? If it always shifts toward the center, I think you can compensate by changing the calibration value closer to the center. For example, try the following .
> 
> ```
>   uint16_t data[8];
> 
>   data[0] =  32;   // left top X
>   data[1] =  32;   // left top Y
>   data[2] =  32;   // left bottom X
>   data[3] = 207;   // left bottom Y
>   data[4] = 287;   // right top X
>   data[5] =  32;   // right top Y
>   data[6] = 287;   // right bottom X
>   data[7] = 207;   // right bottom Y
> 
>   M5.Display.setTouchCalibrate(data);
> ```
> 
> BTW, there is an update to the Core2 touch panel firmware. This reduces the problem of coordinates being shifted vertically at the top of the screen. ( It may have already been updated if your purchase was recent. )
> 
> Try to write `Core2_Tools` once using `M5Burner`. If the touch panel firmware is out of date, `Core2_Tools` will perform the update at startup.
> 
> Once the firmware update is performed, it will remain effective even if other programs are written thereafter.

I installed M5 Tools and it updated the display firmware at startup. Now the touch screen seems to be doing much better.
Thank you

**Comment by lovyan03** [comment]
@gmgunderground 
Congratulations on the improvement of the touch panel performance issue !

Am I correct in assuming that this Issue has been resolved?

**Comment by gmgunderground** [comment]
Now all it's ok
