### ISSUE TITLE
white noise from SPK HAT 

### ISSUE THREAD

**Issue by lkebin** [m5stack/M5Unified#43]
Hello, I'm try to test audio on M5StickC Plus with SPK HAT, using [WebRadio_with_ESP8266Audio.ino] example.

How can I avoid the white noise ? or is it expected from design ?

https://user-images.githubusercontent.com/1335935/205261281-046090bb-7b33-44a1-acd0-28f1f6aca4e7.mp4

**Comment by lovyan03** [comment]
Hello, @lkebin .

There is a hardware circuit problem, which has been resolved in the newly manufactured ones.
If you have soldering skills, you can reduce noise by connecting a capacitor to GND.

![image](https://user-images.githubusercontent.com/42724151/205291617-2198c83c-b42a-43ef-a39e-b17943b085c9.png)

**Comment by lkebin** [comment]
Cool, let me have a try. Thank you !

**Comment by lkebin** [comment]
Better than before, Thanks.
