### ISSUE TITLE
Unified and Timers

### ISSUE THREAD

**Issue by fbritop** [m5stack/M5Unified#49]
We have no longer have access to M5 Timers, how this should be handle?

Thanks

**Comment by lovyan03** [comment]
Hello, @fbritop 
I have added the M5Timer class to the develop branch.
It has not been officially released yet, so if you want to try it out, please get it from the develop branch.

**Comment by lovyan03** [comment]
Hello, @fbritop 
v0.1.3 has been released.
Please try this Issue as it has been resolved.
