### ISSUE TITLE
Missing IMU_Class::getTemp() function declaration

### ISSUE THREAD

**Issue by fxstein** [m5stack/M5Unified#50]
`IMU_Class::getTemp()` is defined in `IMU_Class.hpp`, but not implemented in `IMU_Class.cpp` which leads to a link error when attempting to leverage the function.

Here is a possible implementation for `IMU_Class.cpp`:

```
bool IMU_Class::getTemp(float *t) {
  bool res = false;

  switch (_imu) {
    case imu_t::imu_sh200q:
      res = Sh200q.getTemp(t);
      break;
    case imu_t::imu_mpu6050:
    case imu_t::imu_mpu9250:
    case imu_t::imu_mpu6886:
      res = Mpu6886.getTemp(t);
      break;
    case imu_t::imu_unknown:
    default:
      break;
  }

  return res;
}
```
I hope this helps!

PS: Working on an ESPHome wrapper for m5unified.

**Comment by fxstein** [comment]
BTW Happy to turn this into a pull request if that helps.

**Comment by patfelst** [comment]
> PS: Working on an ESPHome wrapper for m5unified.

Oh I'm very interested in this, if it means I'd be able to use my Core2 with ESPHome!

**Comment by lovyan03** [comment]
Hello, @fxstein  .
Thanks for letting me know! It was very helpful.
A new update release will be prepared this weekend.

**Comment by fxstein** [comment]
Glad I could help! Looking forward to the new release. Thanks!

**Comment by lovyan03** [comment]
Hello, @fxstein 
v0.1.3 has been released.
Please try this Issue as it has been resolved.

**Comment by fxstein** [comment]
Confirmed. This is resolved.
