### ISSUE TITLE
S3 family compilation error: unused variable when compiler_warnings=all

### ISSUE THREAD

**Issue by tobozo** [m5stack/M5Unified#82]
Hi and thanks for this awesome project :+1: 

This line triggers a compilation error when the compiler warnings are at the maximum level in Arduino IDE:

https://github.com/m5stack/M5Unified/blob/855379142da91e4076703019323af3483462c7a6/src/utility/Power_Class.cpp#L527

```log
~/Arduino/libraries/M5Unified/src/utility/Power_Class.cpp: In member function 'bool m5::Power_Class::getUsbOutput()':
~/Arduino/libraries/M5Unified/src/utility/Power_Class.cpp:527:62: error: unused variable 'port0_bitmask' [-Werror=unused-variable]
         static constexpr const uint32_t port0_bitmask = 0b00100000; // USB OTG EN
                                                              ^~~~~~~~~~~~~
cc1plus: some warnings being treated as errors

```

looks like dead code, removing this line doesn't seem to break anything, prefixing `[[maybe_unused]]` works too.

**Comment by lovyan03** [comment]
Hello. @tobozo .
Thanks for pointing out this issue !
We have removed the unnecessary variables and reflected it in the develop branch. This will be reflected in the next release.
