### ISSUE TITLE
H/W infomationにS3系新機種がない

### ISSUE THREAD

**Issue by tanakamasayuki** [m5stack/M5Unified#83]
M5STAMPS3
M5Dial
M5DinMeter
M5Capsule
M5Cardputer

上記がないようです
PR出したほうがよければPRだします！

**Comment by lovyan03** [comment]
ご指摘ありがとうございます、すみません整備が間に合っておらず…。
どこかで時間を作って作業しようとは思っていたのですが、
まだしばらく後回しになりそうなので、PR頂けたら助かります！
